// user promise
export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_FULFILLED = "LOAD_USER_FULFILLED";
export const LOAD_USER_REJECTED = "LOAD_USER_REJECTED";
export const LOAD_USER_PENDING = "LOAD_USER_PENDING";