// user promise
export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_FULFILLED = "LOAD_USER_FULFILLED";
export const LOAD_USER_REJECTED = "LOAD_USER_REJECTED";
export const LOAD_USER_PENDING = "LOAD_USER_PENDING";
export const USER_LOG_OUT = "USER_LOG_OUT";
export const REGISTER = "REGISTER";
export const REGISTER_FULFILLED = "REGISTER_FULFILLED";
export const REGISTER_REJECTED = "REGISTER_REJECTED";
export const REGISTER_PENDING = "REGISTER_PENDING";
export const CLEAR_REGISTER= "CLEAR_REGISTER";